# Generated by Django 3.0.5 on 2021-02-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Latitud')),
                ('altitud', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Altitud')),
            ],
        ),
    ]
