# Generated by Django 3.0.5 on 2021-02-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubications',
            name='altitud',
            field=models.DecimalField(decimal_places=1000, max_digits=1000, verbose_name='Altitud'),
        ),
        migrations.AlterField(
            model_name='ubications',
            name='latitud',
            field=models.DecimalField(decimal_places=1000, max_digits=1000, verbose_name='Latitud'),
        ),
    ]
